# Generated by Django 4.1.2 on 2022-12-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userinfo_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tot_num',
            field=models.BigIntegerField(default=0),
        ),
    ]
