# Generated by Django 4.1.2 on 2022-12-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_category_tot_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
