# Generated by Django 4.1 on 2023-06-09 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_productinfo_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='device_mac_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
